permalink: /:year/:month/:day/:title.html
paginate: 10
highlighter: pygments
markdown: redcarpet

# 作者信息
author: 
  name: John Jin
  email: jinguol999@163.com
  link: http://jinguoliang.github.io
#  weibo: http://weibo.com/orangeissweet
  github: http://github.com/jinguoliang
#  music: http://site.douban.com/linanya
#  linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 金国梁的博客
description: 如果说我装一下x,我会觉得舒服,那也无妨
url: http://jinguoliang.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/head.png
favicon: /public/img/head.png

# google analytics 设置
ga:
  id:  UA-64152187-1
  url: jinguoliang.github.io

# disqus 设置
disqus:
  shortname: disqus_fkdy8oBxeS

# 主题设置，自动激活某个标签
active: 生活

# 首页除了最新文章外显示分类
cates: 
  - Android
  - Linux

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
