#!/bin/sh

title=$1
if test ! -n "$title"
then
	echo need draft name
	exit
fi

if test ! -d _posts
then
  echo no _posts directory, ensure in jekyll project
  exit
fi

if test ! -d draft
then
  echo no draft
  exit
fi

draftfile=draft/$title
if test ! -e $draftfile
then
  echo no this draft
  exit
fi

mv $draftfile _posts
